services:
  rabbitmq:
    image: rabbitmq:4-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - .env
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:8-alpine
    ports:
      - "6379:6379"

  postgres: 
    image: postgres:18-alpine
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
     - type: tmpfs
       target: /dev/shm
       tmpfs:
         size: 134217728 # 128*2^20 bytes = 128Mb

volumes:
  rabbitmq_data:
